### ISSUE TITLE
Print execution time for each test case

### ISSUE THREAD

**Issue by chermehdi** [chermehdi/go-egor#21]
For each test case the example output is: 
```
┌───┬──────────────────┬────────┬────────┬──────────────────┬────────────────────┐
│ # │ TEST NAME        │ STATUS │ CUSTOM │ ADDITIONAL INFOS │ STDERR             │
├───┼──────────────────┼────────┼────────┼──────────────────┼────────────────────┤
│ 0 │ inputs/test-0.in │ AC     │ false  │ None             │                    │
│ 1 │ inputs/test-1.in │ AC     │ false  │ None             │                    │
│ 2 │ inputs/test-2.in │ RE     │ false  │ None             │ This stderr output │
│   │                  │        │        │                  │                    │
└───┴──────────────────┴────────┴────────┴──────────────────┴────────────────────┘
```
Maybe adding another column displaying the execution time and even the time limit something like (123ms/1000ms) can be helpfull.

**Comment by chermehdi** [comment]
@Eroui Where are we on this ?

**Comment by Eroui** [comment]
This issue overlaps with the issue #15.
Been working originally on timed executions (Report Time Limit Exceeded to the user when the execution time passes the defined time limit of the task). 

Had some issues testing it as its hard to test with exact timeouts + delta.
