### ISSUE TITLE
Transform egor into a package (for Linux)

### ISSUE THREAD

**Issue by aymanrs** [chermehdi/go-egor#34]
It will be very nice if we could install egor from a command like `sudo apt install egor` so it can be upgraded without having to reinstall it from Github.

**Comment by chermehdi** [comment]
Are you suggesting that you want to work on it ?

**Comment by aymanrs** [comment]
I don't know Go but I suppose I can create packages and manage them

**Comment by aymanrs** [comment]
https://fedoraproject.org/wiki/Join_the_package_collection_maintainers
https://www.linux.com/news/make-your-own-packages-debian-based-systems/

**Comment by Eroui** [comment]
Creating the debian package is a good idea, and doesn't require a golang language (or at least not so much), but will it really simplify the installation of egor for linux users? 

I don't think the creation of the package is that hard. I made few packages and the past and I can recommend this: https://snapcraft.io/.  I used it once in the past in a slightly complex project and I think it will be easier to use it. I think it evolved so much compared to when I used it, and it does support packaging for many programming languages including go.

**Comment by chermehdi** [comment]
In my opinion it's not a priority to have a linux package, simply because of the additional package that we will need to support, make sure the latest version is on github and at the same time in the linux repositories. the codebase is changing very often i suggest we leave this after hitting `1.0.0`

**Comment by aymanrs** [comment]
in conclusion, it will be better to wait for egor to be more stable then create packages, windows installers...
