### ISSUE TITLE
tests just don't work

### ISSUE THREAD

**Issue by aymanrs** [chermehdi/go-egor#48]
When I try to test my solution in C++ (a.k.a egor works fine with Java and Python) it displays this error:

> 2020/04/08 19:49:30 Cannot find judge for the given lang cpp

**Comment by Eroui** [comment]
I could not reproduce the error, My cpp judge works fine just like the others.
Can you provide a copy of your egor-meta.json in your task ?

**Comment by Eroui** [comment]
Also can you please tell us what egor version do you have? You can get it by running an empty egor command.

**Comment by aymanrs** [comment]
my current version of egor is 0.2.0

**Comment by aymanrs** [comment]
{"TaskName":"B. LCM","TaskLang":"cpp","Inputs":[{"Name":"test-0","Path":"inputs/test-0.in","Custom":false},{"Name":"test-1","Path":"inputs/test-1.in","Custom":false}],"Outputs":[{"Name":"test-0","Path":"outputs/test-0.ans","Custom":false},{"Name":"test-1","Path":"outputs/test-1.ans","Custom":false}],"TaskFile":"main.cpp"}

**Comment by aymanrs** [comment]
I figured out where was the problem, you actually corrected it. All you have to do is to deploy a new release and source code. Btw the error was in the _run.go_ file at line 427 seems like Go doesn't allow this in switch.
