### ISSUE TITLE
Add Support for contest parsing.

### ISSUE THREAD

**Issue by Eroui** [chermehdi/go-egor#58]
Allow go-egor users to be able to parse a whole contest.

Competitive companion can parse all problems in a contest in many CP platforms. 

## Design
Add boolean flag ___--contest___ for the command ___egor parse___.  In the presence of this boolean flag, an integer value is expected (defaulted to  1 in case the user didn't specify one) denoting the number of problems to parse.

The reason why the number of problems is needed is because competitive companion generate consecutive calls and egor parser need to know when it finishes.

**Comment by chermehdi** [comment]
Sounds reasonable, although it would've been nicer for that information to be provided from Chelper companion to avoid hacky solutions or adding unnecessary parameters.

The plans sounds good, Thanks for writing this up.
