### ISSUE TITLE
Maybe a typo in the README file

### ISSUE THREAD

**Issue by moadfakhri** [chermehdi/go-egor#73]
the command for editing the template apparently should be `egor config set custom.templates.{lang} /path/to/template/file` instead of `egor config set config.templates.{lang} /path/to/template/file`

**Comment by Eroui** [comment]
This is not just a typo in the readme file. In fact,  to set a template for a give language  you need to use `egor config set  custom.templates.{lang}`, but to get the path for a custom template you need to use `egor config get config.templates.{lang}`. 

This is a mismatch and needs to be fixed. (Feel free to send a PR to fix it if you want to)

**Comment by moadfakhri** [comment]
ok done
