### ISSUE TITLE
egor test gives WA when run with diff checker

### ISSUE THREAD

**Issue by moadfakhri** [chermehdi/go-egor#77]
![image](https://user-images.githubusercontent.com/37900094/108348295-e3e5ca80-71e1-11eb-847f-511d73e5ddb5.png)

**Comment by chermehdi** [comment]
Yes, that's expected as the checker does a strict string equals checking which is not what most people expect, I suggest you create a PR for this where you replace the default checker with the `tokens` one.

**Comment by moadfakhri** [comment]
Ok done.
